# Configuration file for the Emotiv data simulation and processing pipeline

# Layer 1: Data Source Configuration

# Choose the data source for the pipeline. Options:
# - "emotiv": Use real data from the Emotiv dataset (requires dataset access and preprocessing)
# - "virtual": Use simulated data based on predefined emotional state sequences
pow_data_source: "virtual"  # "emotiv" or "virtual"

# Folder path to save the captured data. This is where the output from the L1 layer will be stored.
L1_output_folder: "L1_band_power_capture/output_data"

## Emotiv headset configuration
# Emotiv streams, specify which streams to capture from the Emotiv dataset.
# It should at least include 'pow', for the band power features, but you can include others as needed for your application.e
emotiv_streams: ["mot", "dev", "eq", "pow", "met", "com", "fac", "sys"]

# Profile name
# Used to name the output folder for the captured data.
# Also used to identify the profile in the Emotiv servers
profile_name: "Emotiv"

## Virtual simulation parameters (only used if pow_data_source is set to "virtual")
# If using virtual data, specify the subject ID to simulate. Set to -1 to simulate all subjects, 
# or choose a specific subject ID (e.g., 4) for focused testing.
# Not every subject in the Emotiv dataset has data for all emotional states, 4 works well enough for testing purposes.
sub_id: 4 

#If using virtual data, you can smoothly transition between emotional states by specifying a transition duration in seconds. 
# Set to 0 for instant transitions, or a positive value (e.g., 1.0) for gradual transitions.
transition_duration: 0  

# If using virtual data, specify the sequence of emotional states to simulate. 
#You can choose from predefined sequences or define your own.
#Expected shape:
# name_nequence:
#  - [emotion_state, duration_in_seconds]
sequences:
  basic:
    - ["frustrated", 1]
    - ["happy", 1]
    - ["angry", 1]
    - ["neutral", 1]
  extended:
    - ["frustrated", 1]
    - ["happy", 1.5]
    - ["angry", 0.5]
    - ["neutral", 1]
  neutral:
    - ["neutral", 5]
  bored_angry:
    - ["bored", 2]
    - ["angry", 2]

## Emotional simulator set up
# Path to the feather file containing the pow data
feather_file_path: "L1_band_power_capture/Simulated_pow/Data/Dreamer/dreamer_bandpower_frames.feather"  
# Define the range of valence and arousal values for the emotional states.
# Used to normalize the simulated emotional states.
emotion_range: [-1.0, 1.0]
# Define the emotional states and their corresponding areas in the valence-arousal space.
emotional_states_areas:
  # Column 1 -> Low Valence [-1.0, -0.3]
  - id: bored
    label: "Bored"
    range:
      valence_min: -1.0
      valence_max: -0.3
      arousal_min: -1.0
      arousal_max: -0.3

  - id: frustrated
    label: "Frustrated/Sad"
    range:
      valence_min: -1.0
      valence_max: -0.3
      arousal_min:  -0.3
      arousal_max: 0.3
      

  - id: angry
    label: "Angry"
    range:
      valence_min: -1.0
      valence_max: -0.3
      arousal_min:  0.3
      arousal_max: 1.0

  # Column 2  -> Mid Valence [-0.3, 0.3]
  - id: tired
    label: "Tired/Sleepy"
    range:
      valence_min: -0.3
      valence_max: 0.3
      arousal_min: -1.0
      arousal_max: -0.3

  - id: neutral
    label: "Neutral"
    range:
      valence_min: -0.3
      valence_max: 0.3
      arousal_min: -0.3
      arousal_max: 0.3

  - id: surprise
    label: "Surprise/Tense"
    range:
      valence_min: -0.3
      valence_max: 0.3
      arousal_min: 0.3
      arousal_max: 1.0

  # Column 3 -> High Valence [0.3, 1.0]
  - id: calm
    label: "Calm"
    range:
      valence_min: 0.3
      valence_max: 1.0
      arousal_min: -1.0
      arousal_max: -0.3

  - id: happy
    label: "Happy/Pleased"
    range:
      valence_min: 0.3
      valence_max: 1.0
      arousal_min: -0.3
      arousal_max: 0.3
  
  - id: excited
    label: "Excited"
    range:
      valence_min: 0.3
      valence_max: 1.0
      arousal_min: 0.3
      arousal_max: 1.0


## Emotiv config 
# Define the columns to be used from the Emotiv dataset for power features.
POW_COLUMNS: [AF3/theta, AF3/alpha, AF3/betaL, AF3/betaH, AF3/gamma, F7/theta, F7/alpha, F7/betaL, F7/betaH, F7/gamma, F3/theta, F3/alpha, F3/betaL, F3/betaH, F3/gamma, FC5/theta, FC5/alpha, FC5/betaL, FC5/betaH, FC5/gamma, T7/theta, T7/alpha, T7/betaL, T7/betaH, T7/gamma, P7/theta, P7/alpha, P7/betaL, P7/betaH, P7/gamma, O1/theta, O1/alpha, O1/betaL, O1/betaH, O1/gamma, O2/theta, O2/alpha, O2/betaL, O2/betaH, O2/gamma, P8/theta, P8/alpha, P8/betaL, P8/betaH, P8/gamma, T8/theta, T8/alpha, T8/betaL, T8/betaH, T8/gamma, FC6/theta, FC6/alpha, FC6/betaL, FC6/betaH, FC6/gamma, F4/theta, F4/alpha, F4/betaL, F4/betaH, F4/gamma, F8/theta, F8/alpha, F8/betaL, F8/betaH, F8/gamma, AF4/theta, AF4/alpha, AF4/betaL, AF4/betaH, AF4/gamma]

epoch_sensors:
  frontal_pairs:
    - [F3, F4]
    - [AF3, AF4]
    - [F7, F8]
  frontal_electrodes: [F3, F4, AF3, AF4, F7, F8, FC5, FC6]
  parietal_pairs:
    - [P7, P8]
  parietal_electrodes: [P7, P8]
  electrodes: [AF3, F7, F3, FC5, T7, P7, O1, O2, P8, T8, FC6, F4, F8, AF4]
  frequency_bands: [alpha, betaL, betaH, theta, gamma]


## Layer 2: Data Processing Configuration
l2_output_folder: "L2_emot_state_estimation/output_data"  # Folder path to save the processed data from Layer 2

## Feature selection configuration for Layer 2
# If it's needed, you can specify wich pow_column you wish to use for the classifier in layer 2. 
# If empty, all columns will be used.
l2_pow_columns: []  # List of pow columns to use for feature selection in Layer 2 (e.g., ["AF3/theta", "F7/alpha"])
# Extra features to add
# Asymmetries and ratios can be powerful features for emotion recognition, as they capture the relative differences in brain activity between different regions. 
# You can specify which asymmetry or ratio features to add to the dataset.
# Format for asymmetries:
# - [area, type, band]
# area: "frontal" or "parietal"
# type: "difference" (for differences) or "ratio" (for ratios). Both will be in log scale
# band: "alpha", "betaL", "betaH", "theta", or "gamma"
asymmetries: 
  - ["frontal", "difference", "alpha"]  
  - ["parietal", "difference", "alpha"]
  - ["frontal", "ratio", "alpha"]

# Implemented: 
# - Hjorth mobility: Measures the mean frequency of the signal, which can reflect the overall activity level in the brain. Higher mobility may indicate more active brain states, while lower mobility may indicate more relaxed states.
# - Hjorth complexity: Measures the complexity of the signal, which can reflect the variability and
features_to_add: []  # List of additional features to add (e.g., ["hjorth_mobility", "hjorth_complexity"])
