# Configuration file for the Emotiv data simulation and processing pipeline

# Layer 1: Data Source Configuration

# Choose the data source for the pipeline. Options:
# - "emotiv": Use real data from the Emotiv dataset (requires dataset access and preprocessing)
# - "virtual": Use simulated data based on predefined emotional state sequences
pow_data_source: "virtual"  # "emotiv" or "virtual"

## Virtual simulation parameters (only used if pow_data_source is set to "virtual")
# If using virtual data, specify the subject ID to simulate. Set to -1 to simulate all subjects, 
# or choose a specific subject ID (e.g., 4) for focused testing.
# Not every subject in the Emotiv dataset has data for all emotional states, 4 works well enough for testing purposes.
sub_id: 4 

#If using virtual data, you can smoothly transition between emotional states by specifying a transition duration in seconds. 
# Set to 0 for instant transitions, or a positive value (e.g., 1.0) for gradual transitions.
transition_duration: 0  

# If using virtual data, specify the sequence of emotional states to simulate. 
#You can choose from predefined sequences or define your own.
#Expected shape:
# name_nequence:
#  - [emotion_state, duration_in_seconds]
sequences:
  basic:
    - ["frustrated", 1]
    - ["happy", 1]
    - ["angry", 1]
    - ["neutral", 1]
  extended:
    - ["frustrated", 1]
    - ["happy", 1.5]
    - ["angry", 0.5]
    - ["neutral", 1]
  neutral:
    - ["neutral", 5]
  bored_angry:
    - ["bored", 2]
    - ["angry", 2]

## Emotional simulator set up
# Define the range of valence and arousal values for the emotional states.
# Used to normalize the simulated emotional states.
emotion_range: [-1.0, 1.0]
# Define the emotional states and their corresponding areas in the valence-arousal space.
emotional_states_areas:
  # Column 1 -> Low Valence [-1.0, -0.3]
  - id: bored
    label: "Bored"
    range:
      valence_min: -1.0
      valence_max: -0.3
      arousal_min: -1.0
      arousal_max: -0.3

  - id: frustrated
    label: "Frustrated/Sad"
    range:
      valence_min: -1.0
      valence_max: -0.3
      arousal_min:  -0.3
      arousal_max: 0.3
      

  - id: angry
    label: "Angry"
    range:
      valence_min: -1.0
      valence_max: -0.3
      arousal_min:  0.3
      arousal_max: 1.0

  # Column 2  -> Mid Valence [-0.3, 0.3]
  - id: tired
    label: "Tired/Sleepy"
    range:
      valence_min: -0.3
      valence_max: 0.3
      arousal_min: -1.0
      arousal_max: -0.3

  - id: neutral
    label: "Neutral"
    range:
      valence_min: -0.3
      valence_max: 0.3
      arousal_min: -0.3
      arousal_max: 0.3

  - id: surprise
    label: "Surprise/Tense"
    range:
      valence_min: -0.3
      valence_max: 0.3
      arousal_min: 0.3
      arousal_max: 1.0

  # Column 3 -> High Valence [0.3, 1.0]
  - id: calm
    label: "Calm"
    range:
      valence_min: 0.3
      valence_max: 1.0
      arousal_min: -1.0
      arousal_max: -0.3

  - id: happy
    label: "Happy/Pleased"
    range:
      valence_min: 0.3
      valence_max: 1.0
      arousal_min: -0.3
      arousal_max: 0.3
  
  - id: excited
    label: "Excited"
    range:
      valence_min: 0.3
      valence_max: 1.0
      arousal_min: 0.3
      arousal_max: 1.0
